#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag azure-servicebus-sender:latest watsonlu/azure-servicebus-sender:latest
docker push watsonlu/azure-servicebus-sender
